### ISSUE TITLE
Possible additions

### ISSUE THREAD

**Issue by violetastcs** [Wilfred/bfc#24]
OK so before you say that this isn't brainfuck if you add more, i know it isn't, but you could make a subset which adds all this (maybe barefuck, idk)

OK so basically my idea was for there to be more features so that we could write the esoteric OS described on the esolang wiki (https://bit.ly/2GiXKxb) in an esoteric language. 

The things I think we would need to implement (some are just to make things slightly easier but still)

- Inline assembly - Possibly inbetween `a` and `z` command? Though this may be problematic.
- Ability to push and pop from the stack - Maybe from a `^` for push and a `v` for pop
- Ability to create a static lib with labels and ability to call other labels - While this would basically implement functions, it would be nessesary for creating an OS

Also, maybe just to keep it a regular bf compiler aswell, you would have to specify an option for it to use this subset.

I know there is little chance that this suggestion will be considered, but it's worth a try :P

**Comment by Wilfred** [comment]
Hi Jacob!

Thanks for looking at bfc :). I'm afraid that I'm not interested in extending bfc. I'd be open to adding common brainfuck extensions, such as `#` or even considering `+[]]` to be a legal program, but I don't have ambitions beyond that.

You are, of course, welcome to fork the project :)
