### ISSUE TITLE
Compilation time is exponential wrt. source size

### ISSUE THREAD

**Issue by nicuveo** [Wilfred/bfc#26]
Hello! In the context of https://github.com/nicuveo/BFS, I am compiling some pretty big brainf*ck files that exceed 1MB, such as https://raw.githubusercontent.com/nicuveo/BFS/tmp/test/tmp.bf (1.1MB), but bfc takes a very long time to compile them (up to twenty minutes). A simple benchmark (see below) seems to suggest that compilation time **is exponential wrt. source size**.

I created a simple program that peforms N time the same operation, and ran bfc 10 times for different values of N to get an estimated average compilation time:

`time for i in {1..10}; do bfc perf_test_$N.bf; done`

[N=1, 94K](https://github.com/Wilfred/bfc/files/2775699/perf_test_1.txt): 0.32s average
[N=2, 187K](https://github.com/Wilfred/bfc/files/2775698/perf_test_2.txt): 3.18s average
[N=3, 281K](https://github.com/Wilfred/bfc/files/2775697/perf_test_3.txt): 26.54s average

I'd be happy to help with a patch if there is an easy workaround, such as disabling some sort of optimiser. Thanks!

**Comment by nicuveo** [comment]
I ran all three with `valgrind --tool=callgrind`; it seems LLVMRunPassManager is the culprit?
[edit] ah, yeah, this seems to be the entry point, so that's not much new info...

**Comment by Wilfred** [comment]
Interesting! FWIW you can try running bfc with `--opt=0` to measure performance without bfc's own optimisation passes.

Speculating wildly, upgrading bfc to use the latest LLVM might help (it's a few versions behind currently).

**Comment by Wilfred** [comment]
This no longer reproduces on bfc 1.11 with LLVM 13, so I think LLVM is now handling this case better.
