### ISSUE TITLE
Panic compiling fizzbuzz.bf

### ISSUE THREAD

**Issue by MagaTailor** [Wilfred/bfc#3]
All examples compile fine except for fizzbuzz.bf, which fails with: 

`thread '<main>' panicked at 'index out of bounds: the len is 3 but the index is 10', src/libcollections/vec.rs:1110`

or 

`thread '<main>' panicked at 'index out of bounds: the len is 3 but the index is 10', src/libcollections/vec.rs:1035`

depending on the custom built target architecture i586 or i686-unknown-linux-gnu respectively.

I'm on 32-bit Linux, using nightly rust and llvm 3.7

**Comment by Wilfred** [comment]
Fixed, thank you! :)

**Comment by MagaTailor** [comment]
I'm not sure if I've found a bug or it's something else but on arm, trying to compile anything ends like this:

`No such file or directory (os error 2)`

The compiler is able to dump IR so it's probably working in all other respects. 

I can't tell from the trace what's wrong, have a look yourself:

https://gist.github.com/petevine/8690f57bc252abc146de

Or is it supposed to work only on x86?  (IR contains `target triple = "i686-pc-linux-gnu"` which is clearly wrong on arm)

**Comment by Wilfred** [comment]
OK, you're not trying to run the executable produced, the error is from running the compiler, correct?

Could you please set `RUST_BACKTRACE=1` in your shell, and run again? That should give you a backtrace.

The compiler should in principle work on ARM, but executables will be for x86 due to the target triple. You could change the target triple, but I worry about the external function declarations:

``` llvm
declare i32 @write(i32, i8*, i32)

declare i32 @putchar(i32)

declare i32 @getchar()
```

These are assuming a 32-bit word size.

Also, you said dumping IR works. Were you referring to dumping bfc IR or LLVM IR? Does something like this work?:

```
$ bfc sample_programs/hello_world.bf --dump-llvm > hello.ll
$ lli hello.ll
```

**Comment by MagaTailor** [comment]
I was referring to llvm-ir and the above fails due to the x86 target. (just the 2nd step)

As for `RUST_BACKTRACE=1` it doesn't produce anything new as the problem lies somewhere in-between - no binary can be produced after all.

I've just noticed I may have a few llvm symlinks missing (like lli -> lli-3.6) so maybe that's the whole problem. 

BTW, arm is 32-bit by definition (aarch64 is 64-bit) so it'd be nice to use bfc on arm as well.

**Comment by Wilfred** [comment]
Yep, you need `llc`, `clang` and `strip` on your `$PATH` in order use bfc. I've pushed a commit to make bfc more helpful.

Do you know what LLVM target triple and datalayout your ARM device needs?

**Comment by MagaTailor** [comment]
Thanks. On armv7 hard-float that I use it's called `arm-unknown-linux-gnueabihf`

https://github.com/rust-lang/rust/blob/master/src/librustc_back/target/arm_unknown_linux_gnueabihf.rs

**Comment by MagaTailor** [comment]
Here's the data layout:

`target datalayout = "e-m:e-p:32:32-i64:64-v128:64:128-a:0:32-n32-S64"`

**Comment by Wilfred** [comment]
FWIW I've just pushed 521ad694f9326f723b1272aa7cd0f49c037aa585 so you should now be able to do:

```
$ bfc your_file.bf --target=arm-unknown-linux-gnueabihf
```

**Comment by MagaTailor** [comment]
Well, well, thought you'd forgotten about this - let me try!

**EDIT:**
Indeed, a working bfc cross-compiler!

**Comment by petevine** [comment]
Indeed, a working bfc cros-compiler!
