### ISSUE TITLE
Segfault due to incorrect target

### ISSUE THREAD

**Issue by MagaTailor** [Wilfred/bfc#9]
Supplying an incorrect target results in a segfault:

```
target/release/bfc --target=x86-linux-gnu sample_programs/hello_world.bf

Program received signal SIGSEGV, Segmentation fault.
0x80ec7ab5 in LLVMCreateTargetMachine ()
(gdb) bt
#0  0x80ec7ab5 in LLVMCreateTargetMachine ()
#1  0x00000000 in ?? ()
```

That's probably just a usability tweak as clang would print an error too:

`clang: error: unsupported option '--triple=x86-linux-gnu'`

**Comment by MagaTailor** [comment]
`No available targets are compatible with this triple, see -version for the available targets.`

There's no `-version` switch in bfc though - was it meant to be `clang --version`?

**Comment by Wilfred** [comment]
This string is generated by LLVM itself. I suspect it's referring to `llc -version`.

I'll send a patch upstream.

**Comment by Wilfred** [comment]
http://reviews.llvm.org/D16028
